version: "3.9"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Az1310750412
      - POSTGRES_DB=salas
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api-atividades:
    build: .
    restart: always
    ports:
      - "8002:8000"
    environment:
      DATABASE_URL:  postgresql://postgres:Az1310750412@177.81.186.211:5432/escola
    depends_on:
      - db
volumes:
  postgres_data: